<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class GeneratePage extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'generate:page {name : The name of the page file} {--layout= : The layout to use for the view} {--force : Overwrite the view file if it exists} {--table= : Create an inline view} {--model= : Create Model an inline view}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command generate views/pages';

    /**
     * Execute the console command.
     */
private function getType($type){
        $types = [
            'string' => 'text',
            'varchar' => 'text',
            'text' => 'textarea',
            'longtext' => 'textarea',
            'int' => 'number',
            'integer' => 'number',
            'bigint' => 'number',
            'date' => 'date',
            'datetime' => 'datetime-local',
            'time' => 'time',
            'boolean' => 'checkbox',
            'float' => 'number',
            'double' => 'number',
            'decimal' => 'number',
            'timestamp' => 'datetime-local',
            'timestampTz' => 'datetime-local',
            'id' => 'text',
            'bigIncrements' => 'text',
            'bigInteger' => 'number',
            'binary' => 'file',
            'boolean' => 'checkbox',
            'char' => 'text',
            'date' => 'date',
            'dateTime' => 'datetime-local',
            'dateTimeTz' => 'datetime-local',
            'decimal' => 'number',
            'double' => 'number',
            'enum' => 'text',
            'float' => 'number',
            'increments' => 'text',
            'integer' => 'number',
            'mediumInteger' => 'number',
            'mediumText' => 'textarea',
        ];
        return $types[$type];

    }
    public function handle()
    {
        //
         // Get the name of the view
         $name = $this->argument('name');
         $layout = $this->option('layout') ?: 'layouts.app';
        $modelName = $this->option('model') ?: Str::studly(Str::singular(class_basename($name)));

         // Create the file path
         $path = resource_path('views/pages/' . str_replace('.', '/', $name) . '.blade.php');

         // Check if the file already exists
         if (File::exists($path)) {
             $this->error("The view file already exists at {$path}");
             return;
         }

         // Ensure the directory exists
         File::ensureDirectoryExists(dirname($path));
        if($this->option('table')){
                $cols = Schema::getColumnListing($this->option('table'));
                $i = 0;
                foreach($cols as $col ){
                    $width = $col == 'id' ? 'style="100px"' : '';
                    $type = $this->getType(Schema::getColumnType($this->option('table'), $col));
                    $typeData = Schema::getColumnType($this->option('table'), $col);

                    if($i!=0){
                        $input[$i] = $i== 1 ?  "\t'". $col ."'=> \$this->".$col."," :   "\t\t\t\t'". $col ."'=> \$this->".$col."," ;
                    }
                  $fields[$i] = $i== 0 ? "\tpublic $". $col ." = '';" : "\t\tpublic $". $col ." = '';";
                  $edit[$i] = $i== 0 ?   "\$this->". $col ." = \$row->". $col .";" : "\t\t\$this->". $col ." = \$row->". $col .";";
                   "\t\t['label'=>'". Str::headline($col) ."',\t'name'=>'". $col ."',\t 'type'=>'".$type."',\t'typeData'=>'".$typeData."']";
                $inputModal[$i] = $col != 'id' && $col != 'created_at' && $col != 'updated_at'  ?"<flux:ui.input.text name=\"$col\"  label=\"".Str::headline($col)."\" type=\"$type\" />" : '';

                  $i++;
                }
                $inputs = implode("\n",$input);
                $inputModals = implode("\n",$inputModal);
                $state = implode("\n",$fields);
                $edits = implode("\n",$edit);
                // $columns = '[]';
            }else{
            $inputs = '';
            $inputModals = '';
            $state = '';
            $edits = '';
            }
$date =  date('Y-m-d H:i:s');

// Generate the file content
$content = <<<PHP
<?php
// Generated by GeneratePage Command
// Date: $date
// Model: $modelName
use function Laravel\Folio\\name;
use function Laravel\Folio\{middleware};
middleware(['auth', 'verified','adminAuth']);
name('admin.$name');
use Livewire\Volt\Component;
use App\Models\\$modelName;
new class extends Component {
    public    \$message= '';
    public \$showModal,
        \$data_id,
        \$showConfirmModal,
        \$showSuccessModal = false;

    //Tambahkan nama column disini

    // public function with(): array
    // {

    // }
    // public function mount(): array
    // {

    // }

    public function save()
    {
        \$this->updated_at = now();
        \$this->updated_at = now();

        \$data = [
              $inputs
        ];
        \$submit = DB::transaction(function () use (\$data) {
            if (\$this->data_id) {
                $modelName::find(\$this->data_id)->update(\$data);
            } else {
                $modelName::create(\$data);
            }
            return true;
        });
        if (\$submit) {
            \$this->reset();
            \$this->message = 'Data berhasil disimpan';
            \$this->showSuccessModal = true;
        }
    }

};
?>
<x-layouts.admin>
 @volt
 <div>
   <div class="mb-3">
        <flux:ui.breadcrumb :links="[['url' => '/', 'label' => 'Home'], ['label' => '$name']]" />
    </div>
    <div class="w-full max-w-lg gap-2 bg-gray-50 dark:bg-gray-700 p-6 border border-default rounded-lg shadow-xs">
        <form wire:submit.prevent="save">
            <div class="space-y-6">
                <h5 class="text-xl font-semibold text-heading mb-6">$name</h5>

                </div>
        </form>
    </div>

<flux:ui.modal.success message="{{ \$message }}" />
    </div>
    @endvolt
</x-layouts.admin>
PHP;

         // Create the file
         File::put($path, $content);

         $this->info("View file created at {$path}");
     }

}
