<?php
// Generated by GeneratePage Command
// Date: 2025-12-28 04:00:58
// Model: Option
use function Laravel\Folio\name;
use function Laravel\Folio\{middleware};
middleware(['auth', 'verified','adminAuth']);
name('admin.pengaturan');
use Livewire\Volt\Component;
use App\Models\Option;
new class extends Component {
    public    $message= '';
    public $showModal,
        $data_id,
        $showConfirmModal,
        $showSuccessModal = false;
    public $option_name,
        $option_value;
        public $site_name, $site_description;
    //Tambahkan nama column disini
    // public function with(): array
    // {
    // }
    public function mount(): void
    {
        $this->site_name = Option::getValue('site_name') ?? '';
        $this->site_description = Option::getValue('site_description') ?? '';
    }
    public function save()
    {
        $submit = false;
        $this->created_at = now();
        $this->updated_at = now();
        $data = [
              	'option_name'=> $this->option_name,
				'option_value'=> $this->option_value,
        ];
        $site_name = Option::where('option_name','site_name')->first();
        $site_description = Option::where('option_name','site_name')->first();
        $submit1 = Option::setValue('site_name', $this->site_name);
        $submit2 = Option::setValue('site_description', $this->site_description);
        if($submit1 && $submit2){
            $submit = true;
        }
        // $submit = DB::transaction(function () use ($data) {
        //     if ($this->data_id) {
        //         Option::find($this->data_id)->update($data);
        //     } else {
        //         Option::create($data);
        //     }
        //     return true;
        // });
        if ($submit) {
            // $this->reset();
            $this->message = 'Data berhasil disimpan';
            $this->showSuccessModal = true;
        }
    }
};
?>
<x-layouts.admin>
 @volt
 <div>
   <div class="mb-3">
        <flux:ui.breadcrumb :links="[['url' => '/', 'label' => 'Home'], ['label' => 'Pengaturan']]" />
    </div>
    <div class="w-full max-w-lg gap-2 bg-white dark:bg-gray-700 p-6 border border-default rounded-lg shadow-xs">
        <form wire:submit.prevent="save">
            <div class="space-y-6">
                <h5 class="text-xl font-semibold text-heading mb-6">Pengaturan</h5>
                    <flux:input label="Site Name" wire:model="site_name" description="Nama situs" />
                    <flux:input label="Site Description" wire:model="site_description" description="Deskripsi situs" />
                    <flux:button variant="primary" type="submit">Save</flux:button>
                </div>
        </form>
    </div>
<flux:ui.modal.success message="{{ $message }}" />
    </div>
    @endvolt
</x-layouts.admin>