<?php
// Generated by GenerateAdmin Command
// Date: 2025-12-28 04:45:48
// Model: User
use function Laravel\Folio\name;
use function Laravel\Folio\{middleware};
middleware(['auth', 'verified','adminAuth']);
name('admin.users');
use Livewire\WithPagination;
use Livewire\Volt\Component;
use App\Models\User;
use Illuminate\Support\Facades\DB;
new class extends Component {
    use WithPagination;
    public    $message,
        $search = '';
    public $showModal,
        $data_id,
        $showConfirmModal,
        $showSuccessModal,
        $showDeleteButton = false;
    public $showCheckAll = true;
    public $searchField = 'name';
    public $limit = 10;
    public $selected = [];
    public $sortField = 'id';
    public $sortDirection = 'desc';
    public $showTimestamp = false;

    //Tambahkan nama column disini

    	public $id = '';
		public $name = '';
		public $email = '';
		public $email_verified_at = '';
		public $password = '';
		public $role = '';
		public $remember_token = '';
		public $created_at = '';
		public $updated_at = '';
		public $two_factor_secret = '';
		public $two_factor_recovery_codes = '';
		public $two_factor_confirmed_at = '';
    public $columns = [
    	['label'=>'Id',	'name'=>'id',	'type'=>'number',	'typeData'=>'integer'],
		['label'=>'Name',	'name'=>'name',	 'type'=>'text',	'typeData'=>'varchar'],
		['label'=>'Email',	'name'=>'email',	 'type'=>'text',	'typeData'=>'varchar'],
		['label'=>'Email Verified At',	'name'=>'email_verified_at',	 'type'=>'datetime-local',	'typeData'=>'datetime'],
		['label'=>'Password',	'name'=>'password',	 'type'=>'text',	'typeData'=>'varchar'],
		['label'=>'Role',	'name'=>'role',	 'type'=>'text',	'typeData'=>'varchar'],
		['label'=>'Remember Token',	'name'=>'remember_token',	 'type'=>'text',	'typeData'=>'varchar'],
		['label'=>'Created At',	'name'=>'created_at',	 'type'=>'datetime-local',	'typeData'=>'datetime'],
		['label'=>'Updated At',	'name'=>'updated_at',	 'type'=>'datetime-local',	'typeData'=>'datetime'],
		['label'=>'Two Factor Secret',	'name'=>'two_factor_secret',	 'type'=>'textarea',	'typeData'=>'text'],
		['label'=>'Two Factor Recovery Codes',	'name'=>'two_factor_recovery_codes',	 'type'=>'textarea',	'typeData'=>'text'],
		['label'=>'Two Factor Confirmed At',	'name'=>'two_factor_confirmed_at',	 'type'=>'datetime-local',	'typeData'=>'datetime']
    ];
    public function mount()
    {
        $user_id = auth()->user()->id;

    }
    public function with(): array
    {
        $limit = $this->limit == null ? 10 : $this->limit;
        $sortField = $this->sortField;
        $sortDirection = $this->sortDirection;
        $data = $this->search == null ? User::orderBy($sortField,$sortDirection) : User::where($this->searchField, 'like', '%' . $this->search . '%')->orderBy($sortField, $sortDirection);
        $data = $data->paginate($limit);
        return [
            'results' => $data,
        ];
    }
    public function sortBy($field)
    {
        $this->sortField = $field;
        $this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc';
    }
    public function create()
    {
        $this->reset();
        $this->mount();
        $this->created_at = date('Y-m-d\TH:i', time());
        $this->updated_at = date('Y-m-d\TH:i', time());
        $this->showModal = true;
    }
    public function save()
    {
        $validated = $this->validate([
        'name' => 'required|string|max:255',
        'email' => 'required|string|email|max:255|unique:users,email,' . $this->data_id,
        'email_verified_at' => 'nullable|date',
        'password' => 'nullable|string|min:8',
        'role' => 'nullable|string|max:255',
        'remember_token' => 'nullable|string|max:100',
        'two_factor_secret' => 'nullable|string',
        'two_factor_recovery_codes' => 'nullable|string',
        'two_factor_confirmed_at' => 'nullable|date',
        ]);
        $data = [
              	'name'=> $this->name,
				'email'=> $this->email,
				'role'=> $this->role,
				'remember_token'=> $this->remember_token,
				'created_at'=> $this->created_at,
				'updated_at'=> $this->updated_at,
				'two_factor_secret'=> $this->two_factor_secret,
				'two_factor_recovery_codes'=> $this->two_factor_recovery_codes,
				'two_factor_confirmed_at'=> $this->two_factor_confirmed_at,
        ];
        // dd($data);
        if ($this->password) {
            $data['password'] = bcrypt($this->password);
        }
        $submit = DB::transaction(function () use ($data) {
            if ($this->data_id) {
                User::find($this->data_id)->update($data);
            } else {
                User::create($data);
            }
            return true;
        });
        if ($submit) {
            $this->reset();
            $this->mount();
            $this->message = 'Data berhasil disimpan';
            $this->showSuccessModal = true;
        }
    }
    public function edit($id)
    {
        $this->reset();
        $row = User::find($id);
        $this->showModal = true;
        $this->data_id = $row->id;
        $this->id = $row->id;
		$this->name = $row->name;
		$this->email = $row->email;
		$this->email_verified_at = $row->email_verified_at;
		$this->password = '';
		$this->role = $row->role;
		$this->remember_token = $row->remember_token;
		$this->created_at = $row->created_at;
		$this->updated_at = $row->updated_at;
		$this->two_factor_secret = $row->two_factor_secret;
		$this->two_factor_recovery_codes = $row->two_factor_recovery_codes;
		$this->two_factor_confirmed_at = $row->two_factor_confirmed_at;
        $this->created_at = date('Y-m-d\TH:i', strtotime($row->created_at));
		$this->updated_at = date('Y-m-d\TH:i', time());
    }
    public function confirmDelete($id)
    {
        $this->showConfirmModal = true;
        $this->data_id = $id;
    }
    public function delete($id = null)
    {
        $id = $id ?? $this->data_id;
        $data = User::find($id);
        if ($data->delete()) {
            $this->toastr = true;
            $this->message = 'Data berhasil dihapus';
            $this->showConfirmModal = false;
            $this->showSuccessModal = true;
            $this->data_id = null;
        }
    }
    public function selectAll()
    {
        $data = $this->selected;
        $this->showDeleteButton = count($data) > 0 ? true : false;
    }
    public function deleteSelected()
    {
        $data = count($this->selected);
        if ($data > 0) {
            User::whereIn('id', $this->selected)->delete();
            $this->selected = [];
            $this->message = 'Data berhasil dihapus';
            $this->showSuccessModal = true;
        }
    }
};
?>
<x-layouts.admin :title="__('User')">
    <div class="mb-3">
        <flux:ui.breadcrumb :links="[['url' => '/', 'label' => 'Home'], ['label' => 'User']]" />
    </div>
    @volt
        <div>
            <flux:modal wire:model.self="showModal" variant="flyout">
                <form wire:submit.prevent="save">
                    <div class="space-y-6">
                        <div>
                            <flux:heading size="lg">Input Data</flux:heading>
                        </div>
                        <flux:input type="hidden" placeholder="ID" wire:model="data_id" />

                        <flux:ui.input.text name="name" label="Name" type="text" />
                        <flux:ui.input.text name="email" label="Email" type="text" />
                        <flux:ui.input.text name="email_verified_at" label="Email Verified At" type="datetime-local" />
                        <flux:input wire:model="password" label="Password" type="password" viewable />
                        <flux:select name="role" label="Role" wire:model="role">
                            <option value="">-- Select Role --</option>
                            <option value="admin">Admin</option>
                            <option value="user">User</option>
                        </flux:select>

                        <flux:ui.input.text name="created_at"
                            label="{{ $showTimestamp ? 'Created At' : '' }}"
                            type="{{ $showTimestamp ? 'datetime-local' : 'hidden' }}" />
                        <flux:ui.input.text name="updated_at"
                            label="{{ $showTimestamp ? 'Updated At' : '' }}"
                            type="{{ $showTimestamp ? 'datetime-local' : 'hidden' }}" />
                        <div class="flex">
                            <flux:spacer />
                            <flux:button variant="primary" type="submit">Save changes</flux:button>
                        </div>
                    </div>
                </form>
            </flux:modal>
            <flux:ui.table.toolbar :showDeleteButton="$showDeleteButton" :showCreateButton=true />
            <flux:ui.table :showCheckAll="$showCheckAll" :message="$message" :results="$results"
                :showDeleteButton="$showDeleteButton">
                <x-slot name="columns">
                    <flux:ui.table.column label="Id" field="id" :sortField="$sortField" :sortDirection="$sortDirection"
                        sortable=true style="100px" />
                    <flux:ui.table.column label="Name" field="name" :sortField="$sortField"
                        :sortDirection="$sortDirection" sortable=true />
                    <flux:ui.table.column label="Email" field="email" :sortField="$sortField"
                        :sortDirection="$sortDirection" sortable=true />
                    <flux:ui.table.column label="Email Verified At" field="email_verified_at" :sortField="$sortField"
                        :sortDirection="$sortDirection" sortable=true />
                    <flux:ui.table.column label="Role" field="role" :sortField="$sortField"
                        :sortDirection="$sortDirection" sortable=true />

                    @if($showTimestamp)
                        <flux:ui.table.column label="Created At" field="created_at" :sortField="$sortField"
                            :sortDirection="$sortDirection" sortable=true />
                        <flux:ui.table.column label="Updated At" field="updated_at" :sortField="$sortField"
                            :sortDirection="$sortDirection" sortable=true />
                    @endif
                    <flux:ui.table.column label="Action" style="width:200px" />
                </x-slot>

                <x-slot name="rows">
                    @foreach($results as $row)
                        <flux:ui.table.row :id="$row->id">
                            @if($showCheckAll)
                                <flux:ui.table.cell :showCheckBox=true :id="$row->id"></flux:ui.table.cell>
                            @endif
                            <flux:ui.table.cell>{{ $row->id }}</flux:ui.table.cell>
                            <flux:ui.table.cell>{{ $row->name }}</flux:ui.table.cell>
                            <flux:ui.table.cell>{{ $row->email }}</flux:ui.table.cell>
                            <flux:ui.table.cell>{{ $row->email_verified_at }}</flux:ui.table.cell>
                            <flux:ui.table.cell>{{ $row->role }}</flux:ui.table.cell>

                            @if($showTimestamp)
                                <flux:ui.table.cell>{{ $row->created_at }}</flux:ui.table.cell>
                                <flux:ui.table.cell>{{ $row->updated_at }}</flux:ui.table.cell>
                            @endif
                            <flux:ui.table.cell style="float: right;">
                                <flux:ui.table.button.action :id="$row->id" :showDetail=false>
                                </flux:ui.table.button.action>
                            </flux:ui.table.cell>
                        </flux:ui.table.row>
                    @endforeach
                </x-slot>
            </flux:ui.table>
        </div>
    @endvolt
</x-layouts.admin>
